name: micro-ROS fork Update Checker
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron:  '0 4 * * *'

jobs:
    micro_ros_fork_update_check:
        runs-on: ubuntu-latest
        container: ubuntu:20.04
        strategy:
          fail-fast: false
          matrix:
            branches: [iron]
        steps:
          - name: Check
            id: check
            shell: bash
            run: |
              apt update; apt install -y git
              REPO=$(echo ${{ github.repository }} | awk '{split($0,a,"/"); print a[2]}')
              git clone -b ${{ matrix.branches }} https://github.com/gardinltd/$REPO
              cd $REPO
              git remote add upstream https://github.com/micro-ros/$REPO
              git fetch upstream
              git fetch origin
              CMP=$(git rev-list --left-right --count upstream/${{ matrix.branches }}...origin/${{ matrix.branches }} | awk '{print $1}')
              if [ $CMP = "0" ]; then
                echo "merge_required=false" >> $GITHUB_OUTPUT
              else
                echo "merge_required=true" >> $GITHUB_OUTPUT
              fi

          - name: Alert
            if: ${{ steps.check.outputs.merge_required  == 'true' }}
            run: exit 1
